# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeduc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('R', 'RIGHT'), ('L', 'LEFT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='strong_arm',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
    ]
