# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeduc', '0002_auto_20170306_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 3, 20, 12, 39, 39, 547004)),
        ),
    ]
