# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeduc', '0004_auto_20170320_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgame',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 20, 12, 48, 10, 196298)),
        ),
    ]
