# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeduc', '0005_auto_20170320_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgame',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 29, 11, 12, 56, 450492)),
        ),
    ]
